version: '2.2'
services:
  mysqldb:
    image: mysql:8.0.26
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=example_db
    volumes:
      - data01:/var/lib/mysql
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=root1234 --execute \"SHOW DATABASES;\""
        interval: 2s
        timeout: 20s
        retries: 10
    expose:
      - 3306
    networks:
      - elastic
  app:
    image: ${user}/demospringboot:v0
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    expose:
      - 8081
    networks:
      - elastic
  app2:
    image: ${user}/demospringboot:v0
    depends_on:
      mysqldb:
        condition: service_healthy
    links:
      - mysqldb
    expose:
      - 8081
    networks:
      - elastic
  loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - app
      - app2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '80:80'
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge